apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: unterbau
  source:
    path: manifests/argocd
    repoURL: https://github.com/MausoleumManagement/argocd.git
    targetRevision: master
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: cert-manager
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: unterbau
  source:
    path: manifests/cert-manager
    repoURL: https://github.com/MausoleumManagement/cert-manager.git
    targetRevision: master
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: cilium
  namespace: argocd
spec:
  destination:
    namespace: cilium
    server: https://kubernetes.default.svc
  project: unterbau
  source:
    path: manifests/cilium
    repoURL: https://github.com/MausoleumManagement/cilium.git
    targetRevision: master
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: cnpg-operator
  namespace: argocd
spec:
  destination:
    namespace: cnpg-system
    server: https://kubernetes.default.svc
  project: unterbau
  source:
    path: manifests/cnpg-operator
    repoURL: https://github.com/MausoleumManagement/cnpg.git
    targetRevision: master
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: csi-nfs
  namespace: argocd
spec:
  destination:
    namespace: csi-nfs
    server: https://kubernetes.default.svc
  project: unterbau
  source:
    path: manifests/csi-nfs
    repoURL: https://github.com/MausoleumManagement/storage.git
    targetRevision: master
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: external-secrets
  namespace: argocd
spec:
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  project: unterbau
  source:
    path: manifests/external-secrets
    repoURL: https://github.com/MausoleumManagement/external-secrets.git
    targetRevision: master
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: hardcoredns
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: unterbau
  source:
    path: manifests/hardcoredns
    repoURL: https://github.com/MausoleumManagement/hardcoredns.git
    targetRevision: master
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: kube-vip-cloud-controller
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: unterbau
  source:
    path: manifests/kube-vip-cloud-controller
    repoURL: https://github.com/MausoleumManagement/kube-vip.git
    targetRevision: master
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: nekropolis-cluster
  namespace: argocd
spec:
  destination:
    namespace: cluster-api
    server: https://kubernetes.default.svc
  project: unterbau
  source:
    path: manifests/nekropolis-cluster
    repoURL: https://github.com/MausoleumManagement/cluster-api.git
    targetRevision: master
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: openbao
  namespace: argocd
spec:
  destination:
    namespace: openbao
    server: https://kubernetes.default.svc
  project: unterbau
  source:
    path: manifests/openbao
    repoURL: https://github.com/MausoleumManagement/openbao.git
    targetRevision: master
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: provider-bootstrap-kubeadm
  namespace: argocd
spec:
  destination:
    namespace: capi-kubeadm-bootstrap-system
    server: https://kubernetes.default.svc
  project: unterbau
  source:
    path: manifests/provider-bootstrap-kubeadm
    repoURL: https://github.com/MausoleumManagement/cluster-api.git
    targetRevision: master
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: provider-capi-core
  namespace: argocd
spec:
  destination:
    namespace: capi-system
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    managedFieldsManagers:
    - clusterrole-aggregation-controller
    name: capi-aggregated-manager-role
  project: unterbau
  source:
    path: manifests/provider-core
    repoURL: https://github.com/MausoleumManagement/cluster-api.git
    targetRevision: master
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: provider-capmox
  namespace: argocd
spec:
  destination:
    namespace: capmox-system
    server: https://kubernetes.default.svc
  project: unterbau
  source:
    path: manifests/provider-capmox
    repoURL: https://github.com/MausoleumManagement/cluster-api.git
    targetRevision: master
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: provider-controlplane-kubeadm
  namespace: argocd
spec:
  destination:
    namespace: capi-kubeadm-control-plane-system
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    managedFieldsManagers:
    - clusterrole-aggregation-controller
    name: capi-kubeadm-control-plane-aggregated-manager-role
  project: unterbau
  source:
    path: manifests/provider-controlplane-kubeadm
    repoURL: https://github.com/MausoleumManagement/cluster-api.git
    targetRevision: master
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: provider-ipam-incluster
  namespace: argocd
spec:
  destination:
    namespace: capi-ipam-in-cluster-system
    server: https://kubernetes.default.svc
  project: unterbau
  source:
    path: manifests/provider-ipam
    repoURL: https://github.com/MausoleumManagement/cluster-api.git
    targetRevision: master
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
