apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-vip-cloud-controller
  #this finaliser causes cascading deletion (delete children)
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
  destination:
    namespace: kube-system
    server: "https://kubernetes.default.svc"
  project: unterbau
  source:
    path: manifests/kube-vip-cloud-controller
    repoURL: "https://github.com/MausoleumManagement/kube-vip.git"
    targetRevision: master
