apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  #this finaliser causes cascading deletion (delete children)
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
  destination:
    namespace: cert-manager
    server: "https://kubernetes.default.svc"
  project: unterbau
  source:
    path: manifests/cert-manager
    repoURL: "https://github.com/MausoleumManagement/cert-manager.git"
    targetRevision: master
