apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
  - application-argocd.yaml
  - application-cert-manager.yaml
  - application-cilium.yaml
  - application-cluster-api.yaml
  - appprojects-unterbau.yaml
