# https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml
# https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/templates/_helpers.tpl
global:
  domain: argocd.irminsul

configs:
  gpg:
    keys:
      F8259EA470CB72D481741F8F7625D1EE0C132087: |
        -----BEGIN PGP PUBLIC KEY BLOCK-----
        
        mDMEaNw1AxYJKwYBBAHaRw8BAQdAIO/nAFEFIiZ7fnYzzVlwbT62HEZQYKEajFju
        37qf9420Ikxlb24gV2VsY2hlcnQgPGxpY2h0dXJtQHBvc3Rlby5kZT6IlgQTFgoA
        PhYhBPglnqRwy3LUgXQfj3Yl0e4MEyCHBQJo3DUDAhsDBQkFo5qABQsJCAcCBhUK
        CQgLAgQWAgMBAh4BAheAAAoJEHYl0e4MEyCHrkkBAMty0IQVQKCBvqHEqEEwsUJL
        MTZTjXmrKP/iCuBCTPXrAQCsNO71qdqeAHl3qV+1mvtMwUlGiv8btK0oIVChSFNI
        Arg4BGjcNQMSCisGAQQBl1UBBQEBB0ARsxZa2hrF524HxNQivBBhn6iyso4DWGAV
        QRiaVSQtEwMBCAeIfgQYFgoAJhYhBPglnqRwy3LUgXQfj3Yl0e4MEyCHBQJo3DUD
        AhsMBQkFo5qAAAoJEHYl0e4MEyCH9PUA+QEsqF3wq7THVvinp7Mp6NQW0N2mGAQ1
        9m3sWZLNozb4AP9t6D01xZDg1Zi7muT+ACdiR5afKAEF3x4YubNxSfA0Dw==
        =TSMI
        -----END PGP PUBLIC KEY BLOCK-----
      22C316A353F6F11ED2693628FD9D433219DA6540: |
        -----BEGIN PGP PUBLIC KEY BLOCK-----
        
        mDMEaNG8nxYJKwYBBAHaRw8BAQdAyZYzGFeocprW5rrlw0wKi5/Tnr+qX1PSm4Aw
        xZUL71+0Ikxlb24gV2VsY2hlcnQgPGxpY2h0dXJtQHBvc3Rlby5kZT6IlgQTFgoA
        PhYhBCLDFqNT9vEe0mk2KP2dQzIZ2mVABQJo0byfAhsDBQkFo5qABQsJCAcCBhUK
        CQgLAgQWAgMBAh4BAheAAAoJEP2dQzIZ2mVAjTQA+wVV7UESwF+HQ2bddio2+EMM
        rB9kJtgymXT5Rrah51dsAPwI1kJYJbbhg+4e0Zi7PpqjYImd3bb4EPYH77u/BOyP
        B7g4BGjRvJ8SCisGAQQBl1UBBQEBB0A2S2JfMY5AFFOMxj7n4TvBk1kADxGtQTTS
        60pESu85JQMBCAeIfgQYFgoAJhYhBCLDFqNT9vEe0mk2KP2dQzIZ2mVABQJo0byf
        AhsMBQkFo5qAAAoJEP2dQzIZ2mVAcewA/0wM4Gfgi1ePoNwksvf2G2tCu9L8U+0H
        M/OZP0vjJ/UoAQCHgcMYzsJndTx/+a9HAIX/bv2nfPWtZGB6jaZmqtzgCLgzBGjR
        vcEWCSsGAQQB2kcPAQEHQBdp1PDrjMq+98E0IPlneFW2p7QW1qZj5h8+Z6R42Oia
        iPUEGBYKACYWIQQiwxajU/bxHtJpNij9nUMyGdplQAUCaNG9wQIbAgUJBaOagACB
        CRD9nUMyGdplQHYgBBkWCgAdFiEEloV47I9tjgZlzjSVRf4BOmOxKz8FAmjRvcEA
        CgkQRf4BOmOxKz82xwEAh9+679XiD20Hm9JVGiCNsOWD9boxYegZcsYwhmMrbmAA
        /jiE9+1udU2pbAro2hIEl0l41rGFjDhVQ7sxin2tdL0O5vYBALLXErpdRb1N8Da7
        RYlujxiU7HHlOX7LD/+jwGi/jKPhAQDMYZzTF5Nx0eYtq6u8RGM3QL8sp6VawrvY
        f1CZbMQFBA==
        =TXFo
        -----END PGP PUBLIC KEY BLOCK-----
      FD9D433219DA6540: |
        -----BEGIN PGP PUBLIC KEY BLOCK-----
        
        mDMEaNG8nxYJKwYBBAHaRw8BAQdAyZYzGFeocprW5rrlw0wKi5/Tnr+qX1PSm4Aw
        xZUL71+0Ikxlb24gV2VsY2hlcnQgPGxpY2h0dXJtQHBvc3Rlby5kZT6IlgQTFgoA
        PhYhBCLDFqNT9vEe0mk2KP2dQzIZ2mVABQJo0byfAhsDBQkFo5qABQsJCAcCBhUK
        CQgLAgQWAgMBAh4BAheAAAoJEP2dQzIZ2mVAjTQA+wVV7UESwF+HQ2bddio2+EMM
        rB9kJtgymXT5Rrah51dsAPwI1kJYJbbhg+4e0Zi7PpqjYImd3bb4EPYH77u/BOyP
        B7g4BGjRvJ8SCisGAQQBl1UBBQEBB0A2S2JfMY5AFFOMxj7n4TvBk1kADxGtQTTS
        60pESu85JQMBCAeIfgQYFgoAJhYhBCLDFqNT9vEe0mk2KP2dQzIZ2mVABQJo0byf
        AhsMBQkFo5qAAAoJEP2dQzIZ2mVAcewA/0wM4Gfgi1ePoNwksvf2G2tCu9L8U+0H
        M/OZP0vjJ/UoAQCHgcMYzsJndTx/+a9HAIX/bv2nfPWtZGB6jaZmqtzgCLgzBGjR
        vcEWCSsGAQQB2kcPAQEHQBdp1PDrjMq+98E0IPlneFW2p7QW1qZj5h8+Z6R42Oia
        iPUEGBYKACYWIQQiwxajU/bxHtJpNij9nUMyGdplQAUCaNG9wQIbAgUJBaOagACB
        CRD9nUMyGdplQHYgBBkWCgAdFiEEloV47I9tjgZlzjSVRf4BOmOxKz8FAmjRvcEA
        CgkQRf4BOmOxKz82xwEAh9+679XiD20Hm9JVGiCNsOWD9boxYegZcsYwhmMrbmAA
        /jiE9+1udU2pbAro2hIEl0l41rGFjDhVQ7sxin2tdL0O5vYBALLXErpdRb1N8Da7
        RYlujxiU7HHlOX7LD/+jwGi/jKPhAQDMYZzTF5Nx0eYtq6u8RGM3QL8sp6VawrvY
        f1CZbMQFBA==
        =TXFo
        -----END PGP PUBLIC KEY BLOCK-----
externalRedis:
  host: valkey
  port: 6379
  existingSecret: argocd-valkey

server:
  service:
    annotations:
      kube-vip.io/loadbalancerIPs: 192.168.13.3
    type: LoadBalancer

redis:
  enabled: false
