apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: bibliophage
  namespace: argocd
spec:
  destination:
    namespace: bibliophage
    server: https://kubernetes.default.svc
  project: tand-nippes-kinkerlitzchen-elaborat
  source:
    path: manifests/bibliophage
    repoURL: https://github.com/GruftGeschoepfe/bibliophage.git
    targetRevision: master
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
